#!/usr/bin/env python3
"""Generate OpeningBookData.java from the Lichess chess-openings database (CC0).

    pip install chess
    python3 scripts/generate_opening_book.py [dir-with-a..e.tsv]

Without a directory argument the five TSV files are downloaded from
https://github.com/lichess-org/chess-openings. Every line is converted to UCI (standard
castling notation, as used by BoardUtil) and stored as "ECO<TAB>name<TAB>uci uci ...".
The table is gzipped and embedded as Base64 string chunks: the extension ships as a
single dex, which cannot carry assets.
"""
import base64, gzip, io, os, sys, urllib.request
import chess, chess.pgn

SRC = "https://raw.githubusercontent.com/lichess-org/chess-openings/master/{}.tsv"
OUT = os.path.join(os.path.dirname(__file__), "..", "extensions", "extension", "src", "main", "java",
                   "app", "prathxm", "chess", "extension", "stockfish", "OpeningBookData.java")

def rows(src_dir):
    for part in "abcde":
        if src_dir:
            text = open(os.path.join(src_dir, part + ".tsv"), encoding="utf-8").read()
        else:
            text = urllib.request.urlopen(SRC.format(part)).read().decode("utf-8")
        for line in text.splitlines()[1:]:
            if line.strip():
                eco, name, pgn = line.split("\t")[:3]
                yield eco, name, pgn

def main():
    src_dir = sys.argv[1] if len(sys.argv) > 1 else None
    out_lines = []
    for eco, name, pgn in rows(src_dir):
        game = chess.pgn.read_game(io.StringIO(pgn))
        board = game.board()
        ucis = []
        for mv in game.mainline_moves():
            ucis.append(mv.uci())
            board.push(mv)
        if not ucis or "\t" in name:
            continue
        out_lines.append(f"{eco}\t{name}\t{' '.join(ucis)}")
    data = gzip.compress("\n".join(out_lines).encode("utf-8"), 9, mtime=0)
    b64 = base64.b64encode(data).decode("ascii")
    chunks = [b64[i:i + 60000] for i in range(0, len(b64), 60000)]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/*\n * Generated by scripts/generate_opening_book.py - do not edit.\n"
                " * Source: Lichess chess-openings (https://github.com/lichess-org/chess-openings), CC0.\n"
                f" * {len(out_lines)} named openings.\n */\n\n")
        f.write("package app.prathxm.chess.extension.stockfish;\n\n")
        f.write("final class OpeningBookData {\n    private OpeningBookData() {}\n\n")
        f.write("    /** Base64 of the gzipped table \"ECO\\tname\\tuci uci ...\" (one opening per line). */\n")
        f.write("    static final String[] GZIP_BASE64 = {\n")
        f.write(",\n".join(f'        "{c}"' for c in chunks))
        f.write("\n    };\n}\n")
    print(f"{len(out_lines)} openings, {len(data)} bytes gzipped, {len(chunks)} chunk(s) -> {os.path.normpath(OUT)}")

if __name__ == "__main__":
    main()
